[tool.poetry]
name = "mori-lint"
version = "0.1.0"
description = ""
authors = ["vrnxx <seryakov78116@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.9.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
